### ISSUE TITLE
Seems working fine so far..

### ISSUE THREAD

**Issue by alikalfaoglu** [nblumhardt/serilog-enrichers-demystify#7]
I'll be happy if you can sign the package before final release.

**Comment by nblumhardt** [comment]
Thanks for the feedback, @alikalfaoglu.

If you need strong naming, you might take a look at https://github.com/dsplaisted/strongnamer, which can be used to add a strong name today.

I'm not planning to add a strong name to this library, but a pull request to add strong naming would be up for consideration if someone submits one.

Thanks!
