### ISSUE TITLE
Q: Works with ASP.NET Core 2.1?

### ISSUE THREAD

**Issue by lonix1** [nblumhardt/serilog-enrichers-demystify#9]
My ASP.NET Core 2.1 app has

    <TargetFramework>netcoreapp2.1</TargetFramework>

When I try `dotnet add package Serilog.Enrichers.Demystify` I get:

````
error: Unable to find a stable package Serilog.Enrichers.Demystify with version
error:   - Found 6 version(s) in nuget.org [ Nearest version: 0.1.0-dev-00002 ]
error: Package 'Serilog.Enrichers.Demystify' is incompatible with 'all' frameworks in project '/foo/myproject.csproj'
````

**Comment by nblumhardt** [comment]
Hi! You'll need to specify the version, `-v  0.1.0-dev-00016`, as there's no "1.0" available for this package.

HTH,
Nick

**Comment by lonix1** [comment]
Thanks that works now!

Do you feel that this package is ready to use in production yet?

Also, I'm curious to see the different between regular and "demystified" exception logs, so I threw some exceptions here and there but they all look the same (with/without this enricher). Is there some good way to test/compare them?

**Comment by nblumhardt** [comment]
.NET Core 2.1 (not sure about Framework equivalent version) introduced much better exception stack traces along these lines, so I don't think this package will ever see a 1.0. Will keep it here for those on earlier versions, though :-)

Cheers!

**Comment by lonix1** [comment]
@nblumhardt I didn't realise that. Makes sense now, because the stack traces I'm seeing with/without this enricher are very very similar! So I've removed it (no offence!! :stuck_out_tongue:)

Thanks for clarifying.

**Comment by nblumhardt** [comment]
:+1:

**Comment by vip32** [comment]
Hi Nicholas,
i just compared the 2 outputs  (netcore 2.1) and there are still significant improvements when using Ben's Demistifier

not demistified
![image](https://user-images.githubusercontent.com/164303/49109760-d7d16380-f28b-11e8-9e1b-dd4b33a8060f.png)

demistified
![image](https://user-images.githubusercontent.com/164303/49109779-e3248f00-f28b-11e8-8d0e-5f8c88a6eb98.png)

maybe meanwhile demystify (0.1.3) has been improved as it definitely shows a better exception. can you reconsider  making a non-preview release of this enricher?

**Comment by nblumhardt** [comment]
Hi @vip32 !

If Ben releases a non-preview version of https://www.nuget.org/packages/ben.demystifier, I'm open to considering it, or helping someone else take over the package to push it ahead 👍

Until there's a non-preview release of that package, there's no way to do this, though: non-preview NuGet packages can't depend on preview ones.

Cheers,
Nick

**Comment by vip32** [comment]
i know, but 1.0.3 is non-preview though
https://www.nuget.org/packages/Ben.Demystifier/0.1.3

i'm happy to take this ... PR?

**Comment by nblumhardt** [comment]
That's 0.1.3, not 1.0.3. Anything with a leading zero is preview in NuGet's eyes :-)

**Comment by vip32** [comment]
not sure about that, as 0.1.3 can be consumed as a normal package without any preview flags (Install-Package Ben.Demystifier). as i know it: semver recognizes previews by the -labels, not the actual versions

**Comment by vip32** [comment]
otherwise a preview notification would be shown here
![image](https://user-images.githubusercontent.com/164303/49112376-d6576980-f292-11e8-9a3d-058be94215cb.png)

**Comment by vip32** [comment]
PR #11  is ready
